# inherit_from: .rubocop_todo.yml

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/EndOfLine:
  EnforcedStyle: lf

Metrics/LineLength:
  Max: 90

Metrics/BlockLength:
  Enabled: false

